### ISSUE TITLE
Filtering a grid on a column that has a valuelist with the "apply valuelist name as filter on column 'valuelist_name'" checkbox checked, does not filter the filter dropdown results

### ISSUE THREAD

**Issue by alexzijlstra-servoy** [Servoy/svyPopupFilter#1]
When I try to filter the data using a column with the above description, I get a drop-down with ALL items from the table instead of it the results getting filtered by the valuelist name. 

Steps to reproduce:
- Create a valuelist with 'Table Values'. Make sure that the checkbox "apply valuelist name as filter on column 'valuelist_name'" is checked. See below screenshot.

![image](https://user-images.githubusercontent.com/30314614/74639851-e5178e00-516e-11ea-9002-fc37215391f0.png)

- Add a column in the data-grid with this valuelist, in this case the filterType is set to 'Text'
- It will now display everything from the table 

No errors/warnings are displayed in Servoy/browser console.

**Comment by paronne** [comment]
Fixed except for scenario where the return dataprovider is the Primarky Key of the table. Will throw a warning in such case. 

Create related case https://github.com/Servoy/svyPopupFilter/issues/2
