### ISSUE TITLE
Using filter (String) not working

### ISSUE THREAD

**Issue by juanetec** [Servoy/svyPopupFilter#10]
Using your svyPopupFilterExample writing in the search input "ana" and creating a city filter "rio" the result is null.
Looking at the Database Performance from de server the query is:
`select orderid from orders  where lower(shipcity) = ? and (upper(customerid) like ? or upper(shipcity) like ? or upper(shipcountry) like ?) order by orderid asc`

![Image 2](https://user-images.githubusercontent.com/26114868/77433119-e0ca3a80-6dd6-11ea-8fc8-b1d3a1185937.png)

I am waching that in the query " where lower(shipcity) = ? " instead of " where lower(shipcity) like ? "

servoy version 2019.12
svyPopupFilter version 1.0.0
svySearch version 1.2.2
svyLookup version 2.0.2
Advanced Renderers version 1.0.1
NG Grids version 2.4.1
Bootstrap Components 2.0.0
12Grid version 1.3.1

Un Saludo

**Comment by seanthomasdevlin** [comment]
Hola juanetec,

The default behavior for the filters is strict (but case-insensitive equals). In the latest version of the component allows to override that. Although I'm now not sure the docs are fully updated on it.

See this issue:
https://github.com/Servoy/svyPopupFilter/issues/3#issuecomment-599411427

**Comment by juanetec** [comment]
Thanks Sean for your quick replay.
This component is incredible an reallly helpful
I will wait for next version.
Thanks
Un Saludo

**Comment by paronne** [comment]
Wiki updated with section: https://github.com/Servoy/svyPopupFilter/wiki#new-default-operator
