### ISSUE TITLE
The proper way for use the i18n in forms.svyTokenPopupFilter

### ISSUE THREAD

**Issue by juanetec** [Servoy/svyPopupFilter#11]
Hi,
I don´t know how is the proper way to implement the i18n in the templates that use this component like forms.svyTokenPopupFilter...
My idea is to create and extended form of this templates an change the names to the i18n way.

Thanks

Un Saludo
Juan Ramírez

**Comment by paronne** [comment]
Hi,
there are no i18n keys for the current filters. It would require a resource project hard to merge with your current resource project.
Currently best option is to extend the existing templates and override the label texts with your own i18n keys.
Check here how to setup & create custom Templates extending the existing filter forms

https://github.com/Servoy/svyPopupFilter/wiki#custom-templates
