### ISSUE TITLE
svyNumberPopupFilter.updateUI() greater then option missing

### ISSUE THREAD

**Issue by juanetec** [Servoy/svyPopupFilter#20]
Hi, 
On the forms.svyNumberPopupFilter.updateUI() greater then option missing
It use the OPERATOR.GREATER_EQUAL but I think it have be OPERATOR.GREATER_THEN or both.
For solving that situation I have extend the form an change It.

Un saludo 

Juan Ramírez

**Comment by paronne** [comment]
Operator was indeed GREATER_EQUAL/SMALLER_EQUAL while the UI says "Greater/Smaller than". Changed the default operator to GREATER_THEN/SMALLER_THEN
