### ISSUE TITLE
Null in a number search

### ISSUE THREAD

**Issue by juanetec** [Servoy/svyPopupFilter#22]
Hi,
Can I do a search at a Numeric PopUp EQUAL null?
In this component of course.

Thanks in advance.

Un Saludo 

Juan Ramírez

**Comment by paronne** [comment]
Hi Juan,

searching for null values is not yet supported for any filter type. I am wondering, does the Numeric PopUp need an option to search for null values ? The user can search for any value greater than 0 or -1, i guess it can be handy only if you have negative values

**Comment by juanetec** [comment]
Hi Paolo you are right, 
but how can I solve if I want for example in an order table who have the field customer_id and I want to search the orders who customer_id  is null?

Un Saludo

Juan Ramírez

**Comment by paronne** [comment]
Hi Juan,

if you are on an order table searching for customer_id, you will probably use a valuelist on the customer_id column. Therefore rather than a Numeric filter you would use a SELECT filter type. However there is not yet any feature to search for null values.

Regards,
Paolo

**Comment by paronne** [comment]
Hi Juan,

the OPERATORs IS_NULL and NOT_NULL has been added to the toolbar filter. Yet there is no default UI to search for Null|Not Null fields. Will be possible to implement your own UI to use such operators by creating custom templates (see wiki on custom templates: https://github.com/Servoy/svyPopupFilter/wiki#custom-templates )

I have created a follow up case, for a later release, to possibily add these operators to the default templates: https://github.com/Servoy/svyPopupFilter/issues/25

Regards,
Paolo
