### ISSUE TITLE
When using the NGDatagrid service to suppress columns, breaks the svyToolbarFilter.js

### ISSUE THREAD

**Issue by tuanway** [Servoy/svyPopupFilter#23]
var toolPanelOptions = plugins.ngDataGrid.createToolPanelConfig(); 
toolPanelOptions.suppressColumnFilter = true; 

![svyToolbarFilter - 1](https://user-images.githubusercontent.com/7150474/80233929-e2c52a80-861c-11ea-9b2e-d270913186d6.png)

**Comment by paronne** [comment]
I could not reproduce the issue; it works just fine following the instructions from wiki https://github.com/Servoy/svyPopupFilter/wiki#disable-default-ng-grid-filters

I can set the column filterType to a value different than NONE and hide the default filter of the table using the suppressColumnFilter

**Comment by tuanway** [comment]
hmm I think this caused by other issues in the search module possibly.  Let's close for now as we cannot reproduce at the moment.
