### ISSUE TITLE
UI Enhancements in filter

### ISSUE THREAD

**Issue by nanjum30** [Servoy/svyPopupFilter#24]
The toolbar filter is providing an excellent filter functionality. There are few UI enhancements in filter, which will take filter toolbar to next level.

1. In tooltip, there must be separating character ":" & a space between Field and Value on which filter is applied. So that user may distinguish between field name and value easily.
For e.g. in below attached screenshot yellow highlighted tooltip must display "Cost Price: 45". (this change is applicable for all search types i.e. Number, Date and Text).![image](https://user-images.githubusercontent.com/52948615/80372834-92183080-88ad-11ea-85fc-693eaed10204.png)

2. For different search types, if a character is added to represent search type in filter display. (This change is applicable for Number and Date only).
a) Bigger than/Later than
In screenshot below, filter is for Product ID bigger than 5.
![image](https://user-images.githubusercontent.com/52948615/80373962-5716fc80-88af-11ea-80eb-97648765c182.png)
If it displays "Product ID > 5", it will directly mentions user that filter is based on bigger than 5.
b) Smaller than/Before than
Similarly, to bigger than. Character can be  "<". e.g.  "Product ID < 5"
c) Equals
Similar to Bigger than. Character can be "=". e.g.  "Product ID = 5"
d)Between
Here, character(">") will be in between two values. e.g. Product ID 2 > 5.

**Comment by paronne** [comment]
Created support issue https://support.servoy.com/browse/SVYX-63 and resolved for coming version.
