### ISSUE TITLE
Related valuelist broke in svyPopupFilter

### ISSUE THREAD

**Issue by juanetec** [Servoy/svyPopupFilter#27]
Hi,
if I use at the aggrid a related valuelist and I try to use the svyPopupFilter.
It broke because it cannot get the datasource from the valuelist.

The problem is in file svyLookup.js line 130 jsList.dataSource return null.
`	dataSource = items.createDataSource(dataSourceName, [JSColumn.TEXT, realValueType], ['realvalue']);
	} else if (jsList.valueListType === JSValueList.DATABASE_VALUES) {
		var jsTable = databaseManager.getTable(jsList.dataSource);
		var pkColumns = jsTable.getRowIdentifierColumnNames();
		`

I make a issue to servoy because I thought that was a servoy bug, but not.
This is the issue:
[https://support.servoy.com/browse/SVY-15042](url)

Un saludo

Juan Ramírez

**Comment by paronne** [comment]
Hi Juan,

the svyLookup module does not support creation of lookup from a related valuelist. See wiki reference: [create-lookup-from-valuelist](https://github.com/Servoy/svyLookup/wiki#create-lookup-from-valuelist).
We added recently support to create a lookup from a global valuelist; that will be available with the next release.
Note a related valuelist requires context of the selected record; the popup filter is meant to list all possible values to filter on (independetly from the selected record in Grid). Therefore implementing and supporting a related valuelist in popup filter can be cumbersome. I believe you can argue the grid may use a related foundset and you wish to use the fk constraint in the filter selection. In this scenario you may setup your own filter using the [OnFilterCreate event](https://github.com/Servoy/svyPopupFilter/wiki#custom-filters)

Regards,
Paolo

**Comment by juanetec** [comment]
Thanks Paolo.
I can use the custom filter for that situations.

Un Saludo

Juan Ramírez
