### ISSUE TITLE
Add option for like filtering

### ISSUE THREAD

**Issue by RvVeen** [Servoy/svyPopupFilter#3]
Currently filters can be set but is always an exact search... nice would be to have filters that can also contain a like think so i want to filter customers starting with serv%

**Comment by paronne** [comment]
Added support for LIKE (will search for SEARCH_WORD%) & LIKE_CONTAINS (will search for %SEARCH_WORD%).

Default operator can be set via global setting "setPopupDefaultOperator(formType, operator)":

```
// global config for grid filters
scopes.svyToolbarFilter.setPopupDefaultOperator(scopes.svyToolbarFilter.FILTER_TYPES.TOKEN, scopes.svyPopupFilter.OPERATOR.LIKE);
```
