### ISSUE TITLE
Valuelist with Custom Values does not work on integer columns

### ISSUE THREAD

**Issue by ruben-stb** [Servoy/svyPopupFilter#35]
When using a valuelist with custom values which is used on an integer column, the query breaks because the lower() function is applied. This happens because the realValues are converted to string values. So there should be a check against the column type of the dataprovider.

**Comment by seanthomasdevlin** [comment]
Hi Ruben, ok thanks.

Planned for 2021.09
https://support.servoy.com/browse/SVYX-268

Do you happen to have an error log / stack trace ?

**Comment by ruben-stb** [comment]
Yup, see attached. I also made a PR with a basic fix.
[stacktrace.txt](https://github.com/Servoy/svyPopupFilter/files/6823429/stacktrace.txt)

**Comment by paronne** [comment]
Resolved. See SVYX-268
