### ISSUE TITLE
Option to add filters true code and not depending on aggrid

### ISSUE THREAD

**Issue by RvVeen** [Servoy/svyPopupFilter#4]
Now it is needed to have al the columns where you want to filter on added into aggrid.
Nicer would be if you can add then in the onload where you init the filtering.

The same option would also be nice to have it working for aditional fields where you want to quicksearch on.

For example table is showing a calculation what is combining the 2 fields into display.
But you want to filter them (can't do it on calculation) what is the same for the search

**Comment by paronne** [comment]
Implemented for version 2.0.0
