### ISSUE TITLE
Add support to Boolean filtering to the svyPopupFilter

### ISSUE THREAD

**Issue by alexzijlstra-servoy** [Servoy/svyPopupFilter#7]
Add support to Boolean filtering to the svyPopupFilter for better Yes/No filtering.

Related ticket
See https://support.servoy.com/browse/SVY-14823

**Comment by paronne** [comment]
Duplicare of support case: SVY-14824

**Comment by paronne** [comment]
Resolved as part of https://support.servoy.com/browse/SVYX-13
